language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t edmorra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edmorra/react-test npm test

after_success:
  - docker build -t edmorra/multi-client ./client
  - docker build -t edmorra/multi-nginx ./nginx
  - docker build -t edmorra/multi-server ./server
  - docker build -t edmorra/multi-worker ./worker
